### ISSUE TITLE
Comaptibility with Django 2.0

### ISSUE THREAD

**Issue by tompecina** [rutube/django_sphinxsearch#35]
Django 2.0 is now stable, but does not work with Sphinxsearch (which only declares to support Django<=1.11). Will it be made comaptible in the foreseeable future?

**Comment by tumb1er** [comment]
The answer is "may be". It depends on developer's free time and a number of internal Django ORM changes.

**Comment by tompecina** [comment]
The patch I'm using (possibly imcomplete) is as follows:

[django-sphinxsearch.patch.txt](https://github.com/rutube/django_sphinxsearch/files/1548931/django-sphinxsearch.patch.txt)

**Comment by tumb1er** [comment]
Well done! 2.0 support is now much closer :)
BTW, what are the reasons for removing sphinxql reserved words escaping?

**Comment by tumb1er** [comment]
please look at https://pypi.python.org/pypi/django_sphinxsearch/2.0.0

Due to some ogranizational reasons Django 2.0 support will be maintained at https://github.com/tumb1er/django_sphinxsearch

**Comment by tompecina** [comment]
Oops, I uploaded the wrong patch! The patch dealing with 2.0 compatibility is this one:

[sphinxsearch-django20.patch.txt](https://github.com/rutube/django_sphinxsearch/files/1550876/sphinxsearch-django20.patch.txt)
